### ISSUE TITLE
"Nothing here" in PhpStorm 8.0.3 on OSX Yosemite

### ISSUE THREAD

**Issue by GuidoHendriks** [vexus2/cake-storm#24]
I'm using CakeStorm in PhpStorm 8.0.3 on the latest OSX Yosemite. When pressing `CMD+; S`, it won't show any files. Are there any known issues with my configuration? Or maybe any suggestions on how to fix this?

**Comment by vexus2** [comment]
Hi. May I Have your cakephp's versions?
