### ISSUE TITLE
CakeStorm 9 doesn't color ctp files

### ISSUE THREAD

**Issue by wp4nuv** [vexus2/cake-storm#28]
... also, should jumping to Model function declarations be available? (Right now CTRL-click on a Model or a Model function returns "Cannot find declaration to go to".  Any suggestions, anyone?

**Comment by vexus2** [comment]
It doesn't support it in the plugin.
Go to  [Preferences] -> [Editor] -> [File Types] -> [PHP]  and add `*.ctp`.
![readme](https://raw.githubusercontent.com/vexus2/CakeStorm/feature/cakephp3/images/readme1.png)
